<div data-bind="scope: 'randomReview'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "randomReview": {
                        "component": "Training_Reviews/js/review",
                            "config": {
                                "template": "Training_Reviews/review",
                                "url": <?= json_encode($block->getUrl('training_reviews/review/index')) ?>
                            }
                    }
                }
            }
        }
    }
</script>
